version: '3.5'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports:
      - '5442:5432'
    networks:
      - conduit

  conduit:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres
      DB_PORT: 5442
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    command: ./gradlew bootRun
    ports:
      - "8080:8080"
    networks:
      - conduit

networks:
  conduit:
    name: conduit
    driver: bridge
